# Generated by Django 4.2.29 on 2026-04-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('futbol_5', 'Fútbol 5'), ('futbol_7', 'Fútbol 7'), ('futbol_8', 'Fútbol 8'), ('futbol_11', 'Fútbol 11')], default='futbol_5', max_length=20)),
                ('superficie', models.CharField(choices=[('sintetica', 'Sintética'), ('natural', 'Natural'), ('piso_duro', 'Piso duro')], default='sintetica', max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=10, help_text='Jugadores por partido')),
                ('precio_por_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='canchas/')),
                ('caracteristicas', models.TextField(blank=True, help_text='Características separadas por línea')),
                ('reglas', models.TextField(blank=True)),
                ('horario_apertura', models.TimeField(default='06:00')),
                ('horario_cierre', models.TimeField(default='22:00')),
                ('es_techada', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Centro Deportivo', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocio/')),
                ('horario_apertura', models.TimeField(default='06:00')),
                ('horario_cierre', models.TimeField(default='22:00')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocio',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('duracion', models.PositiveIntegerField(choices=[(1, '1 hora'), (2, '2 horas'), (3, '3 horas')], default=1)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('cliente_email', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi'), ('pse', 'PSE'), ('wompi', 'Wompi')], default='efectivo', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('abono_30', 'Abono 30%'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nota', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cancha')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
