# Generated by Django 4.2.30 on 2026-05-18 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('bebida', 'Bebida'), ('snack', 'Snack'), ('alquiler', 'Alquiler (guayos, etc.)'), ('servicio', 'Servicio'), ('otro', 'Otro')], default='bebida', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(blank=True, help_text='Dejar vacío para no controlar inventario', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReservaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.PositiveIntegerField(help_text='Hora de inicio (0-23 o 24-29 si cruza medianoche)')),
                ('duracion', models.PositiveIntegerField(choices=[(1, '1 hora'), (2, '2 horas'), (3, '3 horas')], default=1)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('cliente_email', models.CharField(blank=True, max_length=255)),
                ('precio_acordado', models.DecimalField(blank=True, decimal_places=2, help_text='Si está vacío usa el precio normal de la cancha', max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrentes', to='reservas.cancha')),
            ],
            options={
                'verbose_name': 'Reserva recurrente',
                'verbose_name_plural': 'Reservas recurrentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('reserva', models.ForeignKey(blank=True, help_text='Asociar a una reserva (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='reservas.reserva')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_snapshot', models.CharField(help_text='Nombre del producto al momento de la venta', max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaRecurrenteExcepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recurrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='reservas.reservarecurrente')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('recurrente', 'fecha')},
            },
        ),
    ]
