# Generated by Django 4.2.30 on 2026-05-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='tipo',
            field=models.CharField(choices=[('futbol_5', 'Fútbol 5'), ('futbol_7', 'Fútbol 7'), ('futbol_8', 'Fútbol 8'), ('futbol_9', 'Fútbol 9'), ('futbol_11', 'Fútbol 11')], default='futbol_5', max_length=20),
        ),
    ]
