# Generated by Django 4.2.30 on 2026-05-19 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0004_alter_cancha_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno para identificar el par', max_length=30, unique=True)),
                ('color', models.CharField(max_length=40)),
                ('talla', models.PositiveIntegerField(help_text='Talla CO (ej: 38, 40, 42)')),
                ('marca', models.CharField(blank=True, max_length=60)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'Alquilado'), ('mantenimiento', 'En mantenimiento'), ('dado_baja', 'Dado de baja')], default='disponible', max_length=20)),
                ('precio_alquiler', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('nota', models.CharField(blank=True, help_text='Detalles, daños, observaciones', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guayo',
                'verbose_name_plural': 'Guayos',
                'ordering': ['talla', 'color'],
            },
        ),
        migrations.AddField(
            model_name='cancha',
            name='bloquea_canchas',
            field=models.ManyToManyField(blank=True, help_text='Canchas que ocupan el mismo espacio físico (ej: la F-9 son las dos F-7 unidas).', to='reservas.cancha'),
        ),
        migrations.CreateModel(
            name='AlquilerGuayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('cliente_documento', models.CharField(blank=True, help_text='Cédula / documento de garantía', max_length=30)),
                ('fecha_alquiler', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('perdido', 'No devuelto')], default='activo', max_length=15)),
                ('nota', models.TextField(blank=True)),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.cancha')),
                ('guayo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='reservas.guayo')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_guayos', to='reservas.reserva')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_guayos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alquiler de guayos',
                'verbose_name_plural': 'Alquileres de guayos',
                'ordering': ['-fecha_alquiler'],
            },
        ),
    ]
