# Generated by Django 4.2.30 on 2026-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_guayo_cancha_bloquea_canchas_alquilerguayo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprobante',
            field=models.ImageField(blank=True, help_text='Comprobante de transferencia (Nequi, etc.)', null=True, upload_to='comprobantes/'),
        ),
    ]
